# Generated by Django 2.2.2 on 2019-06-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190626_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdashboard',
            name='name',
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='applied_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='reason_to_join',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='resume',
            field=models.FileField(null=True, upload_to='resume/'),
        ),
        migrations.AddField(
            model_name='studentdashboard',
            name='status',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'student'), (3, 'Training_Placement_Officer')]),
        ),
        migrations.AlterField(
            model_name='studentdashboard',
            name='course',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdashboard',
            name='department',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdashboard',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdashboard',
            name='mobno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
