# Generated by Django 2.2.2 on 2019-06-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190630_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='User',
        ),
    ]
