# Generated by Django 2.2.2 on 2019-06-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190630_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='User',
            new_name='user',
        ),
    ]
