# Generated by Django 2.2.2 on 2019-06-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190630_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'student'), (3, 'Training_Placement_Officer')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
