# Generated by Django 2.2.2 on 2019-07-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190701_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.BooleanField(null=True),
        ),
    ]
