# Generated by Django 2.2.2 on 2019-07-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
                ('sem', models.IntegerField()),
                ('department', models.TextField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('mobno', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, null=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('reason_to_join', models.TextField(null=True)),
                ('applied_date', models.DateTimeField(null=True)),
                ('resume', models.FileField(null=True, upload_to='resume/')),
                ('status', models.PositiveSmallIntegerField(default=2)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Studentdashboard',
        ),
    ]
