# Generated by Django 2.2.2 on 2019-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190701_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='email',
            field=models.CharField(max_length=56),
        ),
    ]
