# Generated by Django 2.2.2 on 2019-07-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20190703_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='email',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Submitted'), (2, 'UnderReview'), (3, 'Rejected')], default=0),
        ),
    ]
