# Generated by Django 2.2.2 on 2019-07-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190704_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='button',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Submitted'), (2, 'UnderReview'), (3, 'Rejected'), (4, 'Approved')], default=0),
        ),
    ]
